### ISSUE TITLE
[BUG] - Missing information for LetsEncrypt

### ISSUE THREAD

**Issue by nhcarrigan** [nhcarrigan/code-snippets#11]
# Bug Report

## Describe the bug

The code snippet written for creating an `https` server in `express` is incorrect.

Currently, the snippet instantiates a new server with the line `  const httpsServer = https.createServer(app);`.

## Expected behavior

The `credentials` object needs to be passed to that instantiation as the first parameter:

```ts
  const httpsServer = https.createServer(credentials, app);
```

## Additional information

This looks something that can be fixed by first time contributors to this repository. If you have already made a contribution to this project, please reserve this issue for a new contributor.

Here are the steps to resolve this issue:

- Modify the `docs/notes/lets-encrypt.md` file:
  - Change the `const httpsServer = https.createServer(app);` line to `const httpsServer = https.createServer(credentials, app);`.
  - Be sure to preserve correct indentation

Please make sure you read [our guidelines for contributing](../blob/main/CONTRIBUTING.md). If you have any questions about how to resolve this issue, or about the contributing process in general, [join us in our chat room](http://chat.nhcarrigan.com).

If you are interested in addressing this issue, reply here and we can assign the issue to you. If someone is already assigned to the issue, please allow them time to submit a pull request before requesting to be assigned yourself. Issues are typically unassigned after a week of inactivity.

**Comment by SamDev98** [comment]
I'll do it :)

**Comment by nhcarrigan** [comment]
Go for it 😁

**Comment by SamDev98** [comment]
Done.
