### ISSUE TITLE
[FEAT] Add an issue template for a new script

### ISSUE THREAD

**Issue by jai-dewani** [nhcarrigan/code-snippets#7]
# Feature Request

## Is your feature request related to a problem? Please describe:
I wanted to open a issue for another funny hello world script that I had in mind but I got confused which type of issue this should be. The closest I could think was a Feature request but we can have another Issue template just for new script since this repo is mainly catering to scripts

## Describe the solution you'd like
Just create a new issue template, make sure to have sections in body of issue like 
- The aim of this script
- Section under which this script can be placed
- Language

## Additional context
None

**Comment by nhcarrigan** [comment]
I'm not sure about this one. I definitely do not want this to turn in to a repository of random scripts (the only reason my hello world script is there is I had nowhere else to put it 🤷🏻 )

**Comment by jai-dewani** [comment]
Sure I understand your point of view, there are already enough repositories containing just scripts. So do you have a specific plan for this repo or is it just your personal collection of scripts

**Comment by nhcarrigan** [comment]
This is my personal collection of scripts, notes, and other things I've found helpful.

It's more for my own reference, but enough folks were referring to it that it made sense to publish it as a website.

**Comment by jai-dewani** [comment]
Oh yeah, thanks for making it into a website, I have added it to my list of bookmarks.   
Well I suppose we can close this issue then
